### ISSUE TITLE
^H binding for backspace is missing by default

### ISSUE THREAD

**Issue by stewartstewart-etsy** [strindberg/emacsj#34]
^H, or control-h, a binding that deletes one character backwads, doesn't seem to be included by default in emacsJ

This is a pretty common part of gnu-readline/bash and also shows up in MacOS text fields.

In IntelliJ, it's already bound to type hierarchy. I personally removed that default binding and added a ^H binding for backspace.

**Comment by strindberg** [comment]
Thank you for this. I am a little bit unsure what it is you find missing? Is there something in the plugin's functionality that stops you from remapping control-h to Backspace? Or is it that you would like control-h to be mapped to Backspace in the default EmacsJ keymap?

If it is the latter, I would be reluctant to add it. I agree that it is a common mapping in Unix-like environments, but it's not really a standard Emacs mapping. Moreover it's trivial for any user to create the mapping themselves in Preferences. 

But if I've misunderstood and there is indeed something blocking a re-mapping I would of course be happy to look into it.
