### ISSUE TITLE
Is the EMACSJ_PRIMARY color changeable?

### ISSUE THREAD

**Issue by cpoile** [strindberg/emacsj#57]
Thanks for the great plugin!

Are the `EMACSJ_PRIMARY` and `EMACSJ_SECONDARY` colors changeable? I can't seem to find them in the Color Scheme list.

**Comment by strindberg** [comment]
I don't believe that it's possible at the moment, but I will check how to make it configurable.

**Comment by cpoile** [comment]
Awesome, thank you!
